### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by kmturley** [jlearman/jSfzTools#2]
To let others know what you allow/don't allow, with your code.
It takes two minutes using the GitHub UI to pick from a list of templates:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks!

**Comment by jlearman** [comment]
CC0 license added

**Comment by kmturley** [comment]
Thank-you!
